###

GET http://localhost:4004/wholesalers/getShopDetails(id='8800755400')
###


###
POST http://localhost:4004/wholesalers/getAllShop
Content-Type: application/json

{
    "userId": "aab81d0e-07f4-4922-88bb-215d08093ebe",
    "projectId": "7ff25e2f-b8a7-4586-9fb6-a1530d0e25ca"
}